name: MRI
channels:
- conda-forge
- defaults
dependencies:
- python
- pytorch
- scipy
- h5py
- sympy
- matplotlib
- scikit-learn
- jsonpatch
- packaging
- wandb
- cudatoolkit=11.1
- pip
- pip:
  - fastmri
  - dominate
  - torchvision
  - Pillow
  - numpy
  - visdom
