name: MRI
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python
- pytorch
- scipy
- h5py
- sympy
- matplotlib
- scikit-learn
- jsonpatch
- packaging
- wandb
- cudatoolkit=11.1
- dominate
- pillow
- numpy
- visdom
- pip
- pip:
  - fastmri
  - torchvision
