name: pytorch-CycleGAN-and-pix2pix
channels:
- pytorch
- defaults
dependencies:
- python
- cudatoolkit
- pytorch
- scipy
- pip
- pip:
  - dominate==2.4.0
  - torchvision
  - Pillow==6.1.0
  - numpy==1.16.4
  - visdom==0.1.8
